http:
  routers:
    api:
      rule: HostRegexp(`^traefik\.[a-z]+\.[a-z]+$`)
      entrypoints: websecure
      service: api@internal
      middlewares:
        - tailscale

  middlewares:
    tailscale:
      ipAllowList:
        sourceRange:
          - '100.64.0.0/10'
