networks:
  traefik:
    external: true

services:
  linkding:
    image: sissbruecker/linkding:latest
    restart: unless-stopped
    networks:
      - traefik
    volumes:
      - /srv/linkding-data:/etc/linkding/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bookmarks.rule=Host(`bookmarks.kyswtn.com`)"
      - "traefik.http.routers.bookmarks.entrypoints=websecure"
      - "traefik.http.services.bookmarks.loadbalancer.server.port=9090"
